//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioVisualizerWidget.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AudioVisualizerWidgetServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string SettingsControl_Background {
            get {
                return ResourceManager.GetString("SettingsControl_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        public static string SettingsControl_Foreground {
            get {
                return ResourceManager.GetString("SettingsControl_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph Type:.
        /// </summary>
        public static string SettingsControl_GraphType {
            get {
                return ResourceManager.GetString("SettingsControl_GraphType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalize Volume.
        /// </summary>
        public static string SettingsControl_NormalizeVolume {
            get {
                return ResourceManager.GetString("SettingsControl_NormalizeVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Device:.
        /// </summary>
        public static string SettingsControl_PreferredDevice {
            get {
                return ResourceManager.GetString("SettingsControl_PreferredDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SettingsControl_Save {
            get {
                return ResourceManager.GetString("SettingsControl_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Axis.
        /// </summary>
        public static string SettingsControl_ShowAxis {
            get {
                return ResourceManager.GetString("SettingsControl_ShowAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Grid.
        /// </summary>
        public static string SettingsControl_ShowGrid {
            get {
                return ResourceManager.GetString("SettingsControl_ShowGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Global Theme.
        /// </summary>
        public static string SettingsControl_UseGlobalTheme {
            get {
                return ResourceManager.GetString("SettingsControl_UseGlobalTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizer Density:.
        /// </summary>
        public static string SettingsControl_VisualizerDensity {
            get {
                return ResourceManager.GetString("SettingsControl_VisualizerDensity", resourceCulture);
            }
        }
    }
}
